export enum resultCode {
  OK = 0,
  MAIL_REGISTRED = 1,
  VALIDATION_ERROR = 2,
  USER_NOT_FOUND = 3,
  INVALID_PASSWORD = 4,
  UNAUTHORIZED = 5,
  NOT_MODIFIED = 6,
  DISABLED_USER = 7,
  MAXIMUM_TIME = 8,
  FAIL = 9,
  POST_NOT_FOUND = 10,
  COMMENT_NOT_FOUND = 11,
  FORBIDDEN = 12
}